---
version: 2
updates:
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /mdsf
    schedule:
      interval: daily
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /codegen
    schedule:
      interval: daily
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /docs
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    assignees: [hougesen]
    directory: /
    exclude-paths: [.github/workflows/release.yml]
    schedule:
      interval: weekly
  - package-ecosystem: npm
    assignees: [hougesen]
    directory: /mdsf-vscode
    schedule:
      interval: monthly
  - package-ecosystem: npm
    assignees: [hougesen]
    directory: /github-action
    schedule:
      interval: monthly
