---
version: 2
updates:
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /mdsf
    open-pull-requests-limit: 100
    schedule:
      interval: daily
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /codegen
    open-pull-requests-limit: 100
    schedule:
      interval: daily
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /docs
    open-pull-requests-limit: 100
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    assignees: [hougesen]
    directory: /
    open-pull-requests-limit: 100
    exclude-paths: [.github/workflows/release.yml]
    schedule:
      interval: weekly
  - package-ecosystem: npm
    assignees: [hougesen]
    directory: /mdsf-vscode
    open-pull-requests-limit: 100
    schedule:
      interval: monthly
  - package-ecosystem: npm
    assignees: [hougesen]
    directory: /github-action
    open-pull-requests-limit: 100
    schedule:
      interval: monthly
